name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - develop
jobs:
  build_and_deploy_to_liveServer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: rm -rf node_modules/
      - run: npm install -g firebase-tools
      - run: yarn
      - run: yarn build
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_RRSTUDIO_7893F }}'
          channelId: live
          projectId: rrstudio-7893f
